### ISSUE TITLE
Coding style - comments

### ISSUE THREAD

**Issue by onosek** [fedora-modularity/fus#10]
Please, have mercy with anybody who will help you with the maintaining the code. Without proper comments, it would be painful to understand it. It is even more important until there is no documentation as far as I know. But probably you planned to do it later already.
With main() function splitted into parts, it would be much easier to read it. But I won't be the one who will develop the code further, so I do not mind this much.
Anyway, thanks. This is probably going to be much faster than current depsolving process.

**Comment by lubomir** [comment]
I think this issue can be closed. The code was refactored into smaller parts, and there are also some comments.
