### ISSUE TITLE
Multilib for non-modular packages

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#11]
> No changes to the traditional multilib handling are expected. However, traditional RPM multilib handling needs to be limited to the non-modular part of the compose and shouldn’t affect modular RPMs.

We need to support multilib for non-modular packages. This should be hidden behind an option, so that it can be turned on only for x86_64 and not elsewhere. Also it will need to have a way to configure a whitelist and blacklist.

Current composes support a couple methods for determining what should be multilib. In practice only devel and runtime methods are used. The current implementation [is in Python](https://pagure.io/releng/python-multilib/blob/master/f/multilib/multilib.py#_236-267), so not directly usable.

Expected behaviour:
 * for each package added into the result set, if it matches the rules for multilib or is on the whitelist, and is not on the blacklist, the multilib version should be added
 * dependencies of the multilib package should be resolved too

The rules are horribly complex, and I don't think reimplementing it makes much sense. It would make sense to have a generic rule, and handle exceptions by using the whitelist (which needs to support globs).

The general rules would be
* for `devel` method: any package whose name ends with `-devel` or `-static` should be multilib
* for `runtime` method: if a package installs a file matching `*.so.*` into libdir, it should be multilib

CC @contyk

**Comment by imcleod** [comment]
@lubomir - I really cringe at the notion of duplicating the multi-lib nightmare here.

I'd like to suggest at least a temporary alternative, although you may consider this too ugly.  I believe it should be relatively simple, should unblock you and will avoid the duplication.

For multilib architectures, take the full output of this tool and apply your selection rules to it, using the python code.  Also own the process of doing whitelists and exclusions in that step.  You will end up with a list of additional i686 packages you want included.

Then, run this tool again with that list as the input as pure packages.

Then concatenate the results of the two runs of this tool.

Thoughts?

**Comment by lubomir** [comment]
That would be a possible workaround, except that two passes are not enough. It will have to run repeatedly until nothing is added anymore. Hopefully two passes should be enough.

It still requires a change in this code to support specifying the arch on input package. My expectation of specifying `pkg.arch` does not work (*Error: no solvables matched*).

**Comment by lubomir** [comment]
Closing. The workaround seems to be doing its job.
