### ISSUE TITLE
Selfhosting trees

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#12]
We need an option to follow build dependencies and include them in the result as well. This should be a simple command line option.

**Comment by lubomir** [comment]
This can probably be worked around by explicitly asking to install source rpms. It returns build dependencies, so I think that by running the tool multiple times and explicitly adding the sources as inputs I can get the build dependencies too. Am I missing something?

**Comment by igor-raits** [comment]
Yes, this is what depchase was doing more-or-less.

**Comment by lubomir** [comment]
Since this can be worked around in Pungi, I'll close this issue.
