### ISSUE TITLE
Allow continuing when dependencies are broken

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#13]
Current behaviour when a package has unsatisfiable dependencies is to print an error and exit. This is fine as a default, but there should be an option to continue even in such situation and try to resolve as many dependencies as possible.

Without this it would be impossible to use this code in e.g. Fedora Rawhide. There are always some broken dependencies and aborting on them would mean there would never be a successful compose.

**Comment by igor-raits** [comment]
do you want to still pull broken packages or exclude that package entirely?

**Comment by lubomir** [comment]
Ideally the package should still be included.

**Comment by imcleod** [comment]
Summarizing some realtime discussion on this.

We would like the logic in this tool to make a "best effort" in situations where not all dependencies can be resolved. @ignatenkobrain pointed out that the interaction with libsolv does not easily allow extracting the "partially satisfied transaction"

@contyk suggested an approach which I'll attempt to summarize.  In short, if the tool determines that the transaction cannot be solved, it should iterate through the missing dependencies and create a virtual provides to satisfy them.  It should do this until the transaction is "solved" and then output the fake/virtual provides that were needed, along with the rest of the set of "real" RPMs that need to be included.

@contyk or @ignatenkobrain - please correct me if I've got this wrong.

**Comment by contyk** [comment]
It's correct.

**Comment by lubomir** [comment]
That does seem like a workable approach.

**Comment by imcleod** [comment]
@lubomir - I don't know if you are in a position to hack at this a bit, but I did make one tiny bit of progress, mostly explained in the comments on this branch commit:

https://github.com/imcleod/fus/commit/779067d2ec5bc80004d945ee547c4809667ecf42

**Comment by igor-raits** [comment]
After all I realized that adding provides for missing deps is problematic. Imagine a requires b, b has broken deps, aa requires x, x is provided by b and c, c is installable. When you encounter a, you would pull b and "fix" its broken deps. Then you encounter aa and you pull b, because it's installable. In the end in compose, aa is not installable.

**Comment by igor-raits** [comment]
So lets just pull in main package and don't care about deps. I will push patch shortly.

**Comment by lubomir** [comment]
I tried working on this a bit. I added a new repo for the fake provides (which would allow easy detection in the output), but so far I don't know how to make the new solvable visible for the solver.
https://github.com/lubomir/fus/commit/748e8a720a254aafcad013e5c7d1c9189fb07dc0

**Comment by imcleod** [comment]
@ignatenkobrain - I think I understand what you're saying.  What also makes sense about this is that, ultimately, what the compose user most needs to know is which base/requested package has dependencies that cannot be resolved.  That is, which package in the input set is broken, not the specific point along its dep chain where it breaks.  (I mean, ideally we'd tell people both, but the first part is what's most important.)

What you're proposing sounds like it would then be trivial to track this on a per-input-package basis and flag it in the output, yes?

**Comment by lubomir** [comment]
With current master the process will run to finish, but the result is slightly different than what I expected. If a package has broken deps, it will not be included at all. In my test compose this results in about 27k packages going missing without any trace. It should include the package even if it's dependencies are not there.

**Comment by igor-raits** [comment]
Can you give some example? Also note that it doesn't print broken lookaside packages in output.

**Comment by lubomir** [comment]
I can replicate with a single package and a single comps group that contains it. The package depends on something that does not exist.

```
$ ./builddir/main --verbose --arch x86_64 --repo=repo,repo,/home/lsedlar/.../x86_64/repo group:core
(main:5115): fus-DEBUG: Setting architecture to x86_64
(main:5115): fus-DEBUG: Installing group:core.noarch:
Problem 1 / 1:
  - package group:core.noarch requires dummy-bash, but none of the providers can be installed
  - conflicting requests
  - nothing provides foobar needed by dummy-bash-4.2.37-6.i686
  - nothing provides foobar needed by dummy-bash-4.2.37-6.x86_64

(main:5115): fus-WARNING **: Can't resolve all solvables
group:core.noarch@comps
```

**Comment by igor-raits** [comment]
yes, because comps is metapackage and if its dependencies can't be solved, you just include group itself.

**Comment by lubomir** [comment]
Hmm, so the explicit inputs are always added, but anything else with broken dependencies anywhere in the chain is removed, right?

**Comment by igor-raits** [comment]
As I said earlier, libsolv either resolves all-or-nothing. Since adding "fake providers" has many disadvantages, we can only add main solvable which you requested for solving.

**Comment by lubomir** [comment]
Is there some other way how to get the packages in? There are valid use cases for having packages with broken dependencies.

**Comment by igor-raits** [comment]
The problem here is that comps group is single unit and not just collection of packages. Different dependency chain might result into different path taken. E.g. if comps group references webserver as requirement and both nginx and httpd provide it. Also it lists foo as requirement which has Conflicts: nginx. None of them have broken deps. Solver will choose httpd. But if httpd has broken deps, what should we pull in? There are so many edge cases around that I don't want to go deep into them.

So either you say "comps is not single unit" in which case you probably have to talk to DNF team or fus works as designed.

**Comment by imcleod** [comment]
@ignatenkobrain - Do I understand correctly that the current behavior is that if any package within the comps group fails depsolving, fus includes only the packages explicitly in that group?  That is, if there are 100 packages in the group, and 99 of them depsolv and one does not, fus will currently not pull in the dependencies for the 99, just the 100 group packages?

@lubomir - Could you address this by expanding the groups prior to providing them as input to fus?

**Comment by igor-raits** [comment]
It will pull just group, without packages. Because group is single unit. So
if you want to depsolve all packages in group separately, then you should
process them before getting to fus.--

-Igor Gnatenko

**Comment by lubomir** [comment]
> Could you address this by expanding the groups prior to providing them as input to fus?

That's exactly what I did.
