### ISSUE TITLE
Pulling in bare RPM when module contains an older one

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#33]
Available in the repo:
* module *minput*, contains *input-package* which requires *foo*; module has requires on module *mfoo*
* module *mfoo* contains *foo-1.0-1*
* there's a bare rpm *foo-2.0-1*

When I ask to install module *minput*, I get both versions of *foo* in the output. Is this correct?

CC @contyk 

Attached is a data set that can reproduce that: 
[repr.tar.gz](https://github.com/fedora-modularity/fus/files/2352985/repr.tar.gz)

**Comment by contyk** [comment]
No, it's not. Modular packages need to fully mask ursine ones. You should only get `foo-1.0-1`.

If `input-package` depends on `foo > 1.1`, it would result in a broken dependency as `minput` depends on `mfoo` which makes the `foo` name available, masking the ursine version, yet not providing a version that satisfies the `input-package`'s requirements.

The only way why `foo-2.0-1` would make it into the compose is if a situation where neither `minput` nor `mfoo` are enabled (in the compose case, neither is the default) is possible and something else pulls it in (comps input, dependencies).

**Comment by lubomir** [comment]
There is a somewhat similar case: if a package is listed in comps, should it prefer packages from default modules to bare ones? In such case, should the whole module be pulled in or only the required package? What if user later installs a different stream of the module and the bare rpm from comps becomes possibly uninstallable?

Any hints, @contyk?

**Comment by contyk** [comment]
If a package listed in comps is present in a module enabled by default, you take it from the module.
A module enabled by default is exactly that -- enabled. You depsolve it (and all of its packages) anyway, I hope, so this shouldn't affect anything else.

**Comment by contyk** [comment]
Also if a non-default stream requires the ursine package, you will discover that when depsolving that other, non-default stream, and will pull it in.
