### ISSUE TITLE
Remove the PID from logs

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#36]
The logs contain process id for lines with debug, warning or error severity. For info it's missing.

It would be nice to remove that. It's not really useful and makes diffing the logs a lot harder and less convenient.

**Comment by igor-raits** [comment]
that's coming from glib.

**Comment by lubomir** [comment]
Are there any advantages in using logging from glib instead of using something custom?
Glib logging has some downsides: including unimportant stuff like pid, and printing to both stdout and stderr.

**Comment by r4f4** [comment]
@lubomir setting the environment variable `G_MESSAGES_PREFIXED` to empty will remove `(fus: PID)` from the log lines.
`G_MESSAGES_PREFIXED= ./fus <args>`

See [glib-running documentation](https://developer.gnome.org/glib/stable/glib-running.html)

**Comment by igor-raits** [comment]
> Are there any advantages in using logging from glib instead of using something custom?

Yes, not re-inventing the wheel.

**Comment by igor-raits** [comment]
Thanks @r4f4 for hint.

**Comment by lubomir** [comment]
Cool, adding an env var would work. Thank you very much!
