### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by r4f4** [fedora-modularity/fus#37]
It would be good to have some tests (for functionality and regression) to avoid bugs like #31. Currently I have a test developed by @lubomir for #34. Other tests are needed though, e.g, to test module alternatives.
I'm thinking about creating pkgs specs and a `modules.yaml` and use them to generate a repo. Then we'd run fus on this repo testing the different resolution paths. Another idea is to have a repo per test case.
@ignatenkobrain do you have any input/preferences about this?

**Comment by igor-raits** [comment]
I agree that tests are needed. make sure to use glib test framework ;)

do not create pkgs, just create libsolv test cases and modules.yaml and use testcase_add_testtags in order to load it.

**Comment by r4f4** [comment]
I'm going to close this issue. We have an easy way to add tests since #40 was merged and other tests are being added as we see issues and resolve them.
