### ISSUE TITLE
Lookaside is not handled correctly

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#44]
If the same RPM (with the same NEVRA) is present in both regular repo and in lookaside repo, it should never appear in the output.

However that is not the case. If the package is explicitly listed as input, it will be taken from whichever repo was given first. In such case the the lookasides has to be listed first.

If the package is pulled in as a dependency of another package, I'm not sure how it is selected.

A test case for the first situation follows. The order of repos has to be reversed in `tests.c` for the test to fail (add normal repo first, and then add the lookaside).
```
$ cat input 
pkg
$ cat expected 
$ cat packages.repo 
=Ver: 2.0

=Pkg: pkg 1 1 noarch
$ cat lookaside.repo 
=Ver: 2.0

=Pkg: pkg 1 1 noarch
```

For the second:
```
$ cat input 
foo
$ cat expected 
foo-1-1.x86_64@repo
$ cat packages.repo 
=Ver: 2.0

=Pkg: foo 1 1 noarch
=Req: pkg

=Pkg: pkg 1 1 noarch
$ cat lookaside.repo 
=Ver: 2.0

=Pkg: pkg 1 1 noarch
```

**Comment by igor-raits** [comment]
Does it matter if default is set or not?

**Comment by lubomir** [comment]
Do you mean default stream?
The tests use only bare rpms with no modules.

**Comment by igor-raits** [comment]
Is there any case where we need to prefer lookaside PKG over bare?

**Comment by lubomir** [comment]
If the package is in both repos, we always want to treat it as if it was only in lookaside, so never include it in the output.

This assumes the same NVR. If the versions are different, we probably want the latest version. This case is not a big deal though.

**Comment by igor-raits** [comment]
> If the package is in both repos, we always want to treat it as if it was only in lookaside, so never include it in the output.

Are you sure about this? Even NEVRA is same, content might be different.

In any case, the fix for this is just one line. Just make sure to tell me correct information.

\cc @contyk

**Comment by lubomir** [comment]
I'm pretty sure.

Out of curiosity, do you know how would for example DNF handle repo that contains two different packages with the same NEVRA?

**Comment by igor-raits** [comment]
@lubomir it depends on the `cost` setting in repo configuration (and also `priority`, but we can leave this out).

**Comment by contyk** [comment]
Also pretty sure :)
