### ISSUE TITLE
Optional packages in comps group are not included

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#6]
If a comps group includes a package marked as optional, it will not be pulled into the result.

This is possibly wrong, since if the output is used to generate a repo, users of the repo will not have a chance to install the optional packages at all.

**Comment by igor-raits** [comment]
FTR, `type=optional` works like `Suggests` -- not pulled in as a dependencies.

**Comment by lubomir** [comment]
One place where missing optional packages would be an issue is in Anaconda: when selecting packages for installation, `optional` packages should be shown available for installation (but default off), `default` packages should be enabled by default with option to remove them, and mandatory are installed with no options (they may even not be shown).

**Comment by igor-raits** [comment]
@lubomir there is no package selection nowadays in anaconda...

**Comment by lubomir** [comment]
That's possible, I got this information with "it used to be like this". I'll try to find out why there are optional packages in comps then, if they aren't ever used.

**Comment by lubomir** [comment]
I'm going to close this one. Ultimately the comps groups are going to be expanded into package lists, so this is not an issue.
