### ISSUE TITLE
Add ability to consume repositores over HTTP

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#61]
Currently the input repository has to be located on a local filesystem. It would be useful to allow consuming packages from repos served over HTTP. Fus should transparently download the files as needed.

**Comment by igor-raits** [comment]
@lubomir so are you going to send a patch? :)

**Comment by lubomir** [comment]
Probably not in the nearest future, which is why I'm opening the issue in case there's anyone interested in contributing.
