### ISSUE TITLE
Packages matching glob are included for all arches

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/fus#8]
When the input specifies a package name with a glob, all arches matching that glob are pulled in.

Ideally I think only the best matching architecture should be pulled in.

**Comment by lubomir** [comment]
It does not necessarily need to be a glob, even a package name is sufficient to demonstrate this. Specifying `dummy-bash` pulls in both `x86_64` and `i686`.

Having a way to explicitly say the arch we want would be nice, but specifying `dummy-bash.x86_64` leads to some deadlock or something. Following output is printed and then the process just uses 100% of CPU and does not print anything else:

```
$ ./builddir/main --repo=repo-1,repo,/home/lsedlar/repos/pungi/tests/_composes/DP-1.0-20180626.t.17/work/x86_64/repo/ --debug dummy-bash.x86_64
number of solvables: 64, memory used: 3 K
number of ids: 289 + 74
string memory used: 1 K array + 5 K data,  rel memory used: 0 K array
provide ids: 77
provide space needed: 181 + 256
shrunk whatprovidesdata from 181 to 171
shrunk whatprovidesauxdata from 181 to 101
whatprovides memory used: 5 K id array, 1 K data
whatprovidesaux memory used: 1 K id array, 0 K data
WARNING: pool_addfileprovides was not called, this may result in slow operation
lazywhatprovidesq size: 0 entries
createwhatprovides took 0 ms
```

**Comment by igor-raits** [comment]
The reason for deadlock is that it doesn't find package with name
`foo.x86_64` and since selection is empty, it loops. I will add some
guarding for this.

> --

-Igor Gnatenko
